import Foundation

struct ProfileDataConstants{
    static let path = "profile/set"
    static let email = "email"
    static let firstName = "first_name"
    static let lastName = "last_name"
    static let phone = "phone"
    static let location = "location"
    static let fbId = "fb_id"
    static let vkId = "vk_id"
    static let telegramId = "telegram_id"
    static let id = "id"
    static let gender = "gender"
    static let maleGender = "m"
    static let femaleGender = "f"
    static let loyaltyId = "loyalty_id"
    static let loyaltyStatus = "loyalty_status"
    static let loyaltyBonuses = "loyalty_bonuses"
    static let loyaltyToNextLevel = "loyalty_bonuses_to_next_level"
    static let age = "age"
    static let loyaltyCardLocation = "loyalty_card_location"
    static let birthday = "birthday"
    static let boughtSomething = "bought_something"
    static let calendarYearDateFormat = "yyyy-MM-dd"
    static let weekYearDateFormat = "YYYY-MM-dd"
}
