use_frameworks!
platform :ios, '12.0'

target 'REES46Demo' do
  pod 'REES46', :path => '../'

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
  target 'REES46Tests' do
    inherit! :search_paths
    
  end
end


#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        xcconfig_path = config.base_configuration_reference.real_path
#        xcconfig = File.read(xcconfig_path)
#        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
#        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
#    end
#  end
#end
