use_frameworks!
platform :ios, '11.0'

target 'REES46Demo' do
  pod 'REES46', :path => '../'

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
  target 'REES46Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'REES46'
                config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'Yes'
            end
        end
    end
end
