name: Sync repositories

on:
  workflow_run:
    workflows:
      - "Bump version, create release and publish"
    types:
      - completed
  workflow_dispatch:

jobs:
  run:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    uses: rees46/workflow/.github/workflows/reusable-ios-synchronization.yaml@refactor/reusable-ios-synchronization
    permissions: write-all
    secrets:
      privateKey: ${{ secrets.PERSONACLICK_COURIER_SECRET }}
    with:
      appId: ${{ vars.PERSONACLICK_COURIER_ID }}
      versionFilePath: version.properties
      repositoryOwner: personaclick
      targetRepository: personaclick/ios-sdk
      sourceDirname: "REES46"
      targetDirname: "PersonaClick"
      sourceFilename: "REES46.podspec"
      targetFilename: "PersonaClick.podspec"
      syncIgnore: ".git,.idea,.github/workflows/sync.yaml,.gitignore,Readme.md,DemoApp,version.properties"
      replacementExtentions: "*.swift,*.podspec,*.xib,*.md,*.yaml,LICENSE"
      replacementContents: "https://api.rees46.com/|https://api.personaclick.com/,api.rees46.com|api.personaclick.com,rees46.com|personaclick.com,rees46|personaClick,REES46|PersonaClick,Rees46|PersonaClick"
