name: Sync repositories

on:
  workflow_run:
    workflows:
      - "Bump version, create release and publish"
    types:
      - completed
  workflow_dispatch:

jobs:
  run:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    uses: rees46/workflow/.github/workflows/reusable-ios-synchronization.yaml@master
    permissions: write-all
    secrets:
      token: ${{ secrets.JADE_SMITH_BOT_TOKEN }}
    with:
      repositoryOwner: personaclick
      targetRepository: personaclick/ios-sdk
      sourceDirname: "REES46"
      targetDirname: "PersonaClick"
      syncIgnore: ".git,.idea,.github,.gitignore,Readme.md,DemoApp,REES46.podspec,version.properties"
      replacementExtentions: "*.swift,*.podspec,*.xib,"
      replacementContents: "https://api.rees46.com/|https://api.personaclick.com/,api.rees46.com|api.personaclick.com,rees46.com|personaclick.com,rees46|personaClick,REES46|PersonaClick,Rees46|PersonaClick"
