name: Sync repositories

on:
  workflow_run:
    workflows:
      - "Bump version, create release and publish"
    types:
      - completed
  workflow_dispatch:

jobs:
  run:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    uses: rees46/workflow/.github/workflows/reusable-ios-synchronization.yaml@master
    permissions: write-all
    secrets:
      token: ${{ secrets.JADE_SMITH_BOT_TOKEN }}
    with:
      targetRepository: personaclick/ios-sdk
