name: Sync repositories

on:
  workflow_run:
    workflows:
      - "iOS create release and publish"
    types:
      - completed
  workflow_dispatch:

jobs:
  run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: rees46/workflow/.github/workflows/reusable-ios-synchronization.yaml@master
    permissions: write-all
    secrets:
      token: ${{ secrets.JADE_SMITH_BOT_TOKEN }}
